#  Copyright Mitra Mirshafiee, 2022 Licensed under MIT License.
#  See the LICENSE.txt for more information.


import streamlit as st
from PIL import Image
import os

image = Image.open(os.path.join("assets", "NLP1.png"))
st.image(image, use_column_width  = True)
st.markdown("[source](https://www.steadforce.com/blog/natural-language-processing-tools)")

# display topic input slot
st.title("What is NLP?", "")
st.markdown("""
Natural language processing (NLP) refers to the branch of computer science—and more specifically, 
the branch of artificial intelligence or AI—concerned with giving computers the ability to 
understand text and spoken words in much the same way human beings can.

NLP combines computational linguistics—rule-based modeling of human language—with 
statistical, machine learning, and deep learning models. 
Together, these technologies enable computers to process human language in the
form of text or voice data and to understand its full meaning, 
complete with the speaker or writer's intent and sentiment.

NLP drives computer programs that translate text from one language to another, 
respond to spoken commands, and summarize large volumes of text rapidly—even in real time. 
There's a good chance you've interacted with NLP in the form of voice-operated GPS systems,
digital assistants, speech-to-text dictation software, customer service chat bots, and other consumer conveniences. 
But NLP also plays a growing role in enterprise solutions that help streamline business operations,
increase employee productivity, and simplify mission-critical business processes.
""")
st.markdown("[*](https://www.ibm.com/cloud/learn/natural-language-processing#:~:text=Natural%20language%20processing%20(NLP)%20refers,same%20way%20human%20beings%20can.)")


st.title("What is Question Answering in NLP?")
st.markdown("""
Question Answering models are able to retrieve the answer to a question from a given text.
    This is useful for searching for an answer in a document.
    Depending on the model used, the answer can be directly extracted from text or generated from scratch.
""")
st.markdown("[*](https://medium.com/nlplanet/two-minutes-nlp-quick-intro-to-question-answering-124a0930577c)")


st.title("What are some types of Q&A?")
st.markdown("""
QA systems differ in the way answers are created.

- Extractive QA: The model extracts the answer from a context and provides it directly to the user. It is usually solved with BERT-like models.
- Generative QA: The model generates free text directly based on the context. 
It leverages Text Generation models.
Moreover, QA systems differ in where answers are taken from.

- Open QA: The answer is taken from a context.
- Closed QA: No context is provided and the answer is completely generated by a model.

Based on the definitions above, our model is an **extractive QA** with answers
taken from a text.""")

We're using NLP models from [HuggingFace.com](https://huggingface.co/).
    The pipeline is connected to the `distilbert-base-uncased-distilled-squad` model which you can
    read more about in [here](https://huggingface.co/distilbert-base-uncased-distilled-squad?context=The+Amazon+rainforest+%28Portuguese%3A+Floresta+Amaz%C3%B4nica+or+Amaz%C3%B4nia%3B+Spanish%3A+Selva+Amaz%C3%B3nica%2C+Amazon%C3%ADa+or+usually+Amazonia%3B+French%3A+For%C3%AAt+amazonienne%3B+Dutch%3A+Amazoneregenwoud%29%2C+also+known+in+English+as+Amazonia+or+the+Amazon+Jungle%2C+is+a+moist+broadleaf+forest+that+covers+most+of+the+Amazon+basin+of+South+America.+This+basin+encompasses+7%2C000%2C000+square+kilometres+%282%2C700%2C000+sq+mi%29%2C+of+which+5%2C500%2C000+square+kilometres+%282%2C100%2C000+sq+mi%29+are+covered+by+the+rainforest.+This+region+includes+territory+belonging+to+nine+nations.+The+majority+of+the+forest+is+contained+within+Brazil%2C+with+60%25+of+the+rainforest%2C+followed+by+Peru+with+13%25%2C+Colombia+with+10%25%2C+and+with+minor+amounts+in+Venezuela%2C+Ecuador%2C+Bolivia%2C+Guyana%2C+Suriname+and+French+Guiana.+States+or+departments+in+four+nations+contain+%22Amazonas%22+in+their+names.+The+Amazon+represents+over+half+of+the+planet%27s+remaining+rainforests%2C+and+comprises+the+largest+and+most+biodiverse+tract+of+tropical+rainforest+in+the+world%2C+with+an+estimated+390+billion+individual+trees+divided+into+16%2C000+species.&question=Which+name+is+also+used+to+describe+the+Amazon+rainforest+in+English%3F).
